### ISSUE TITLE
can you give a classifier model?

### ISSUE THREAD

**Issue by kingvision** [cvjena/artos#1]
i did not download the imagenet images, can you provide a pre-train modle?
thanks!

**Comment by Callidior** [comment]
It is not necessary to download the entire ImageNet dataset. Getting just the images and annotations for the synset you're interested in will be sufficient.
So, there should be no problem in learning your own model using ARTOS. Since there are over 3600 synsets with bounding box annotations available on ImageNet and each of those needs specific parameters tuning, we can not provide pre-trained models.
